name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: run-hello
        run: echo "Hello World!!"
      - name: run-goodbye
        run: echo "Goodbye World!!"
    
